# Site Settings
baseurl: ""
url : "https://jeloychavez.github.io"

# Blog Settings
theme_settings :
  title : tan(x)
  favicon : assets/favicon.ico
  blog : "> tan(x) blog "

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Tania R. Zúñiga
    description : Computer Engineering student at Universidad Autónoma Metropolitana. 
    experience :
      - start : 24 / 11 / 2020
        end : Until now
        experience : UAM, School Monitor
      - start : 04 / 05 / 2020
        end : 13 / 11 / 2020
        experience : UAM, PAEA Facilitator
    skills : 
      - skill : BS in Computer Engineering
        value : 75 # Percent value
     
        
  # Icons
  icons :
    email: tania@tanx.dev  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/tania-r-zuniga/ # Full URL 
    github: TanZng
    gitlab: tanx.dev
    bitbucket: 
    google_plus:
    twitter: tanx_dev
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : https-tanzng-github-io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
#gems: [jekyll-paginate, jekyll-sitemap]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
bootstrap:
  assets: true
