# Site Settings
baseurl: ""
url : "https://stonks.company/"

# Blog Settings
theme_settings :
  title : Eloy_dev
  favicon : assets/favicon.ico
  blog : "> Eloy_Dev-Blog "

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Eloy Chavez
    description : Developer student in Platzi. 
    experience :
      - start :  03 / 2020
        end : Until now
        experience : UCA, Systems Assistant
    skills : 
      - skill : Google Cloud Platform
        value : 12 # Percent value
      - skill : JS Challenge
        value : 60
     
        
  # Icons
  icons :
    email: laneloychavez@gmail.com  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/jesus-eloy-chavez-gonzalez-602002213/ # Full URL 
    github: jeloychavez
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: StonksCompany
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : eloy-dev

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
#gems: [jekyll-paginate, jekyll-sitemap]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
bootstrap:
  assets: true
