# Site Settings
baseurl: ""
url : "https://jeloychavez.github.io"

# Blog Settings
theme_settings :
  title : Eloy_dev
  favicon : assets/favicon.ico
  blog : "> Eloy_Dev-Blog "

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Eloy Chavez
    description : Developer student Platzi. 
    experience :
      - start :  03 / 2020
        end : Until now
        experience : UCA, Systems Assistant
    skills : 
      - skill : BS in Computer Engineering
        # value : 75 # Percent value
     
        
  # Icons
  icons :
    email: tania@tanx.dev  # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/tania-r-zuniga/ # Full URL 
    github: TanZng
    gitlab: tanx.dev
    bitbucket: 
    google_plus:
    twitter: tanx_dev
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : https-tanzng-github-io

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
#gems: [jekyll-paginate, jekyll-sitemap]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
bootstrap:
  assets: true
